config/routes.rb
Rails.application.routes.draw do
  resources :social_media_posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/custom_list.rb
class CustomList < ApplicationRecord
  belongs_to :team
  validates :name, presence: true
end

app/models/custom_list_person.rb
class CustomListPerson < ApplicationRecord
  belongs_to :custom_list
  has_many :social_media_people_identifiers, as: :identifiable
  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/models/federal_legislator.rb
class FederalLegislator < ApplicationRecord
  has_many :social_media_people_identifiers, as: :identifiable
  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/models/social_media_people_identifier.rb
class SocialMediaPeopleIdentifier < ApplicationRecord
  belongs_to :social_media_type
  belongs_to :identifiable, polymorphic: true
  has_many :social_media_posts
  validates :identifier, presence: true

end

app/models/social_media_post.rb
class SocialMediaPost < ApplicationRecord
  belongs_to :social_media_people_identifier
  validates :content, presence: true
  validates :post_url, presence: true

  scope :between_dates, ->(start_date, end_date) {
    if start_date.present? && end_date.present?
      where("posted_at >= ? AND posted_at <= ?", start_date.to_date.beginning_of_day, end_date.to_date.end_of_day)
    else
      all
    end
  }

  scope :by_social_media_type, ->(social_media_type) {
    if social_media_type.present?
      joins(social_media_people_identifier: :social_media_type).where("social_media_types.name ilike ?", social_media_type)
    else
      joins(social_media_people_identifier: :social_media_type)
    end
  }

  scope :by_custom_list, ->(custom_list_id) {
    if custom_list_id.present?
      joins(:social_media_people_identifier).where("social_media_people_identifiers.identifiable_id = ?", custom_list_id)
    else
      joins(:social_media_people_identifier)
    end
  }

  scope :by_identifiable_type, ->(identifiable_type) {
    if identifiable_type.present?
      joins(:social_media_people_identifier).where("social_media_people_identifiers.identifiable_type = ?", identifiable_type)
    else
      joins(:social_media_people_identifier)
    end
  }
end

app/models/social_media_type.rb
class SocialMediaType < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/social_media_posts_controller.rb
class SocialMediaPostsController < ApplicationController
  before_action :set_social_media_post, only: %i[ show edit update destroy ]

  # GET /social_media_posts or /social_media_posts.json
  def index
    @social_media_posts = SocialMediaPost.between_dates(params[:start_date], params[:end_date])
                                         .by_social_media_type(params[:social_media_type])
                                         .by_custom_list(params[:custom_list_id])
                                         .by_identifiable_type(params[:identifiable_type])
  end

  # GET /social_media_posts/1 or /social_media_posts/1.json
  def show
  end

  # GET /social_media_posts/new
  def new
    @social_media_post = SocialMediaPost.new
  end

  # GET /social_media_posts/1/edit
  def edit
  end

  # POST /social_media_posts or /social_media_posts.json
  def create
    @social_media_post = SocialMediaPost.new(social_media_post_params)

    respond_to do |format|
      if @social_media_post.save
        format.html { redirect_to social_media_post_url(@social_media_post), notice: "Social media post was successfully created." }
        format.json { render :show, status: :created, location: @social_media_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @social_media_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /social_media_posts/1 or /social_media_posts/1.json
  def update
    respond_to do |format|
      if @social_media_post.update(social_media_post_params)
        format.html { redirect_to social_media_post_url(@social_media_post), notice: "Social media post was successfully updated." }
        format.json { render :show, status: :ok, location: @social_media_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @social_media_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /social_media_posts/1 or /social_media_posts/1.json
  def destroy
    @social_media_post.destroy

    respond_to do |format|
      format.html { redirect_to social_media_posts_url, notice: "Social media post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_social_media_post
      @social_media_post = SocialMediaPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def social_media_post_params
      params.require(:social_media_post).permit(:postable_id, :postable_type, :posted_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/social_media_posts_helper.rb
module SocialMediaPostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialMediaChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/social_media_posts/_form.html.erb
<%= form_with(model: social_media_post) do |form| %>
  <% if social_media_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(social_media_post.errors.count, "error") %> prohibited this social_media_post from being saved:</h2>

      <ul>
        <% social_media_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :postable_id, style: "display: block" %>
    <%= form.text_field :postable_id %>
  </div>

  <div>
    <%= form.label :posted_at, style: "display: block" %>
    <%= form.datetime_field :posted_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/social_media_posts/_social_media_post.html.erb
<div id="<%= dom_id social_media_post %>">
  <p>
    <strong>Content:</strong>
    <%= social_media_post.content %>
  </p>

  <p>
    <strong>Social Media:</strong>
    <%= social_media_post.social_media_people_identifier.social_media_type.name %>
  </p>

  <p>
    <strong>Posted at:</strong>
    <%= social_media_post.posted_at %>
  </p>
</div>

app/views/social_media_posts/edit.html.erb
<h1>Editing social media post</h1>

<%= render "form", social_media_post: @social_media_post %>

<br>

<div>
  <%= link_to "Show this social media post", @social_media_post %> |
  <%= link_to "Back to social media posts", social_media_posts_path %>
</div>

app/views/social_media_posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Social media posts</h1>

<%= form_tag social_media_posts_path, method: :get do %>
  <label for="start_date">Start Date:</label>
  <%= date_field_tag :start_date, params[:start_date] %>

  <label for="end_date">End Date:</label>
  <%= date_field_tag :end_date, params[:end_date] %>

  <label for="social_media_type">Social Media Type:</label>
  <%= select_tag :social_media_type, options_from_collection_for_select(SocialMediaType.all, :name, :name, params[:social_media_type]), include_blank: true %>

  <label for="custom_list">Custom List:</label>
  <%= select_tag :custom_list_id, options_from_collection_for_select(CustomList.all, :id, :name, params[:custom_list_id]), include_blank: true %>

  <label for="identifiable_type">Table:</label>
  <%= select_tag :identifiable_type, options_for_select(['CustomListPerson', 'FederalLegislator'], params[:identifiable_type]), include_blank: true %>


  <%= submit_tag "Filter" %>
<% end %>

<div id="social_media_posts">
  <% @social_media_posts.each do |social_media_post| %>
    <%= render social_media_post %>
    <p>
      <%= link_to "Show this social media post", social_media_post %>
    </p>
  <% end %>
</div>

<%= link_to "New social media post", new_social_media_post_path %>

app/views/social_media_posts/new.html.erb
<h1>New social media post</h1>

<%= render "form", social_media_post: @social_media_post %>

<br>

<div>
  <%= link_to "Back to social media posts", social_media_posts_path %>
</div>

app/views/social_media_posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @social_media_post %>

<div>
  <%= link_to "Edit this social media post", edit_social_media_post_path(@social_media_post) %> |
  <%= link_to "Back to social media posts", social_media_posts_path %>

  <%= button_to "Destroy this social media post", @social_media_post, method: :delete %>
</div>